
[site]
url = "https://2d2d.io"
name = "TO-D 杂志"
description = "专注于探讨全球 To-D 领域相关产品、创业公司、融资等资讯的专栏杂志。"
locale = "zh"
menu = [
  { name = "关于", url = "/about" },
  { name = "博客", url = "/blog" },
  { name = "读者好评", url = "/review" },
  { name = "赞助", url = "/sponsor" },
  { name = "Github", url = "https://github.com/zineland/2d2d" },
]

[authors]
folyd = { avatar = "/static/avatar/folyd.jpg", editor = true, bio = """
<p class="text-center">
《TO-D 杂志》责任编辑，目前就职于字节跳动
</p>

> 申明：个人文章仅代表个人观点，与雇主无关。

可以通过如下方式联系到我：
- [博客](https://folyd.com)
- [Github](https://github.com/folyd)
- [Twitter](https://twitter.com/_hisriver)
- [Telegram](https://t.me/hisriver)
""" }

[theme]
primary-color = "#ffb52f"
main-color = "#000"
link-color = "#e07312"
background-image = "/static/pattern.svg"
footer-template = "templates/footer.html"

[[issue]]
slug = "s1"
number = 1
title = "第一季"
path = "content/issue-1"
intro = "content/issue-1/intro.md"

[[issue]]
slug = "s2"
number = 2
title = "第二季"
path = "content/issue-2"
