slug = "s2"
number = 2
title = "第二季"
publish = true

[[article]]
slug = "deislabs"
file = "1-deislabs.md"
title = "微软 Deis Labs 的故事"
author = "Folyd"
cover = "/static/s2/1/deislabs.png"
pub_date = "2022-04-02"
featured = true
publish = true

[[article]]
slug = "yc-w22"
file = "2-yc-w22.md"
title = "YC 2022 冬季营 DevTools 公司一览"
author = "Tianzhou"
cover = "/static/s2/2/yc-w22.png"
pub_date = "2022-04-06"
featured = true
publish = true

[[article]]
slug = "warp"
file = "3-warp.md"
title = "终端的困境与 Warp 的野心"
author = "Folyd"
cover = "/static/s2/3/warp-cover.jpg"
pub_date = "2022-04-11"
featured = true
publish = true
