[[article]]
slug = "deislabs"
file = "1-deislabs.md"
title = "微软 Deis Labs 的故事"
author = "Folyd"
cover = "/static/s2/1/deislabs.png"
pub_date = "2022-04-02"
featured = true
publish = true

[[article]]
slug = "yc-w22"
file = "2-yc-w22.md"
title = "YC 2022 冬季营 DevTools 公司一览"
author = "Tianzhou"
cover = "/static/s2/2/yc-w22.png"
pub_date = "2022-04-06"
featured = true
publish = true

[[article]]
slug = "warp"
file = "3-warp.md"
title = "TO-D 观察｜小小的终端何以撬动千万美元资本"
author = "Handong Zhang"
cover = "/static/s2/3/warp.png"
pub_date = "2022-04-09"
featured = true
publish = true